In [4]:
import numpy as np
import pandas as pd

Topics: 
• GroupBy mechanics,
• Data aggregations,
• Group-wise operations and transformations,
• pivot tables and cross-tabulations.

In [5]:
df = pd.read_excel("sales.xlsx", sheet_name="Sheet2")
df

        region product  sales  qty
0        urban       a      1    8
1        urban       b      2    9
2        urban       c      3   22
3        urban       d      4   24
4        rural       a      5   23
5        rural       b      6   23
6        rural       c      7   16
7        rural       d      8   15
8   semi-urban       a      9   12
9   semi-urban       b     10   12
10  semi-urban       c     11    9
11  semi-urban       d     12   13
12       urban       a      1   19

In [6]:
# GroupBy
# equivalent to for each unique value the groupby field, compute the agg func on the supplied value columns

In [7]:
df['sales'].groupby(df["product"]).mean()

product
a    4.0
b    6.0
c    7.0
d    8.0
Name: sales, dtype: float64

In [8]:
df['sales'].groupby([df["region"],df["product"]]).sum()

region      product
rural       a           5
            b           6
            c           7
            d           8
semi-urban  a           9
            b          10
            c          11
            d          12
urban       a           2
            b           2
            c           3
            d           4
Name: sales, dtype: int64

In [9]:
# same as above. if there are more numeric columns, they can be included with sales.
df.groupby(['region', 'product'])[['sales', 'qty']].sum()

                    sales  qty
region     product
rural      a            5   23
           b            6   23
           c            7   16
           d            8   15
semi-urban a            9   12
           b           10   12
           c           11    9
           d           12   13
urban      a            2   27
           b            2    9
           c            3   22
           d            4   24

In [10]:
# just for curiosity: multiple aggregate functions
df.groupby(['region', 'product'])['sales'].aggregate(['min', 'max'])

                    min  max
region     product
rural      a          5    5
           b          6    6
           c          7    7
           d          8    8
semi-urban a          9    9
           b         10   10
           c         11   11
           d         12   12
urban      a          1    1
           b          2    2
           c          3    3
           d          4    4

In [11]:
# just for curiosity: this can be handy in developing reports
# groupby multiple columns, aggregate value columns using different sets of functions
df.groupby(['region', 'product']).aggregate({'sales': 'mean', 'qty': ['min', 'max']})

                   sales qty
                    mean min max
region     product
rural      a         5.0  23  23
           b         6.0  23  23
           c         7.0  16  16
           d         8.0  15  15
semi-urban a         9.0  12  12
           b        10.0  12  12
           c        11.0   9   9
           d        12.0  13  13
urban      a         1.0   8  19
           b         2.0   9   9
           c         3.0  22  22
           d         4.0  24  24

In [12]:
for i,group in df.groupby(["product"]):
    #print(i)
    print(group)

        region product  sales  qty
0        urban       a      1    8
4        rural       a      5   23
8   semi-urban       a      9   12
12       urban       a      1   19
       region product  sales  qty
1       urban       b      2    9
5       rural       b      6   23
9  semi-urban       b     10   12
        region product  sales  qty
2        urban       c      3   22
6        rural       c      7   16
10  semi-urban       c     11    9
        region product  sales  qty
3        urban       d      4   24
7        rural       d      8   15
11  semi-urban       d     12   13

In [13]:
for i,j in df.groupby(["region","product"]):
    print(i)
    print(j)

('rural', 'a')
  region product  sales  qty
4  rural       a      5   23
('rural', 'b')
  region product  sales  qty
5  rural       b      6   23
('rural', 'c')
  region product  sales  qty
6  rural       c      7   16
('rural', 'd')
  region product  sales  qty
7  rural       d      8   15
('semi-urban', 'a')
       region product  sales  qty
8  semi-urban       a      9   12
('semi-urban', 'b')
       region product  sales  qty
9  semi-urban       b     10   12
('semi-urban', 'c')
        region product  sales  qty
10  semi-urban       c     11    9
('semi-urban', 'd')
        region product  sales  qty
11  semi-urban       d     12   13
('urban', 'a')
   region product  sales  qty
0   urban       a      1    8
12  urban       a      1   19
('urban', 'b')
  region product  sales  qty
1  urban       b      2    9
('urban', 'c')
  region product  sales  qty
2  urban       c      3   22
('urban', 'd')
  region product  sales  qty
3  urban       d      4   24

In [14]:
# Data aggregations
# these functions produce scalar values summarizing arrays or series objects

In [15]:
df.head(0)

Empty DataFrame
Columns: [region, product, sales, qty]
Index: []

In [16]:
df

        region product  sales  qty
0        urban       a      1    8
1        urban       b      2    9
2        urban       c      3   22
3        urban       d      4   24
4        rural       a      5   23
5        rural       b      6   23
6        rural       c      7   16
7        rural       d      8   15
8   semi-urban       a      9   12
9   semi-urban       b     10   12
10  semi-urban       c     11    9
11  semi-urban       d     12   13
12       urban       a      1   19

In [18]:
df[['sales','qty','region']].groupby("region").sum()

            sales  qty
region
rural          26   77
semi-urban     42   46
urban          11   82

In [19]:
# .agg can be used to then feed in methods or user defined functions
df.groupby("region").agg(sum)

C:\Users\ssridhar\AppData\Local\Temp\ipykernel_22952\3267326168.py:2: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby("region").agg(sum)

           product  sales  qty
region
rural         abcd     26   77
semi-urban    abcd     42   46
urban        abcda     11   82

In [15]:
df.groupby("region")['sales'].agg(["mean"])

            mean
region
rural        6.5
semi-urban  10.5
urban        2.2

In [16]:
# define a function that summarizes grouped value column
# here it is range
def sales_summary(sales):
    return sales.max() - sales.min()

In [17]:
df.groupby("region")['sales'].agg(["mean", sales_summary])

            mean  sales_summary
region
rural        6.5              3
semi-urban  10.5              3
urban        2.2              3

In [18]:
# summary statistics
df['sales'].groupby(df["region"]).describe()

            count  mean       std  min   25%   50%    75%   max
region
rural         4.0   6.5  1.290994  5.0  5.75   6.5   7.25   8.0
semi-urban    4.0  10.5  1.290994  9.0  9.75  10.5  11.25  12.0
urban         5.0   2.2  1.303840  1.0  1.00   2.0   3.00   4.0

# pivot tables and cross-tabulations

In [19]:
df

        region product  sales  qty
0        urban       a      1    8
1        urban       b      2    9
2        urban       c      3   22
3        urban       d      4   24
4        rural       a      5   23
5        rural       b      6   23
6        rural       c      7   16
7        rural       d      8   15
8   semi-urban       a      9   12
9   semi-urban       b     10   12
10  semi-urban       c     11    9
11  semi-urban       d     12   13
12       urban       a      1   19

In [20]:
# index speifies the row, columns the columns, values is aggregated, aggfunc is the function used to summarize values
df.pivot_table(index=["region"],columns=["product"], values=["sales"], aggfunc=["count"])

           count
           sales
product        a  b  c  d
region
rural          1  1  1  1
semi-urban     1  1  1  1
urban          2  1  1  1

# crosstab
is like pivot table, it computes group frequencies

In [21]:
# margins is to show row and col totals
pd.crosstab(df["region"], df["product"], margins=True)

product     a  b  c  d  All
region
rural       1  1  1  1    4
semi-urban  1  1  1  1    4
urban       2  1  1  1    5
All         4  3  3  3   13

In [22]:
titanic = pd.read_csv("titanic.csv")
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
pd.crosstab(index=titanic.Sex, columns=titanic.Embarked)

Embarked   C   Q    S
Sex
female    73  36  203
male      95  41  441

In [24]:
# can be used to check if survival was dependent on Sex by using Chi Square test
pd.crosstab(index=titanic.Sex, columns=titanic.Survived, margins=True)

Survived    0    1  All
Sex
female     81  233  314
male      468  109  577
All       549  342  891

In [25]:
# similar approach as earlier. index (rows), columns (cols), values & aggfunc to populate the cross-section of rows x cols
pd.crosstab(index=titanic.Sex, columns=titanic.Survived, values=titanic.Age, aggfunc="mean", margins=True)

Survived          0          1        All
Sex
female    25.046875  28.847716  27.915709
male      31.618056  27.276022  30.726645
All       30.626179  28.343690  29.699118